version: '3'
services:
  postgres-db:
    image: postgres
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postgres
  mariadb-db:
    image: "mariadb"
    ports:
      - "4306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=sql
  web:
    image: springboot-app
    depends_on:
      - postgres-db
      - mariadb-db
    ports:
      - "8081:8081"
